# Generated by Django 3.2.4 on 2024-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255, verbose_name='学员姓名')),
                ('studentAge', models.IntegerField(blank=True, null=True, verbose_name='学员年龄')),
            ],
            options={
                'verbose_name': '学员信息管理',
            },
        ),
    ]
