# Generated by Django 3.2.4 on 2024-04-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=16, verbose_name='联系方式')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='学生信息')),
            ],
            options={
                'verbose_name': '联系方式',
            },
        ),
    ]
