# Generated by Django 3.2.4 on 2024-04-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '联系方式', 'verbose_name_plural': '联系方式列表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学员信息管理', 'verbose_name_plural': '学员信息列表'},
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=16, verbose_name='联系方式')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='考试信息')),
            ],
            options={
                'verbose_name': '考试信息1',
                'verbose_name_plural': '考试信息1列表',
            },
        ),
    ]
