# Generated by Django 3.2.4 on 2024-04-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20240414_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='score',
            field=models.IntegerField(max_length=16, verbose_name='分数'),
        ),
        migrations.CreateModel(
            name='ExamDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(max_length=16, verbose_name='分数')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='考试详情')),
            ],
            options={
                'verbose_name': '考试详情1',
                'verbose_name_plural': '考试详情1列表',
            },
        ),
    ]
